### ISSUE TITLE
Does it support 3.0.3 redmine version? 

### ISSUE THREAD

**Issue by Silverjack** [centosadmin/redmine_activity_report#1]
When I executed "bundle exec rake redmine:plugins:migrate", I got the following error:

(in /opt/redmine-3.0.3-0/apps/redmine/htdocs)
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/opt/redmine-3.0.3-0/apps/redmine/htdocs/app/models/custom_field.rb:32:in `<class:CustomField>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/app/models/custom_field.rb:18:in`<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:83:in `field_attributes'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:86:in`class:Base'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:48:in `<module:FieldFormat>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:19:in`module:Redmine'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:18:in `<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine.rb:38:in`<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/config/initializers/30-redmine.rb:6:in `<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/config/environment.rb:14:in`<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/plugins/a_common_libs/lib/tasks/saas.rake:1:in `<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in`block in <top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `each'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in`<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
bash-4.1# bundle exec rake redmine:plugins:migrate
(in /opt/redmine-3.0.3-0/apps/redmine/htdocs)
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/opt/redmine-3.0.3-0/apps/redmine/htdocs/app/models/custom_field.rb:32:in`class:CustomField'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/app/models/custom_field.rb:18:in `<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:83:in`field_attributes'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:86:in `<class:Base>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:48:in`module:FieldFormat'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:19:in `<module:Redmine>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine/field_format.rb:18:in`<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/redmine.rb:38:in `<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/config/initializers/30-redmine.rb:6:in`<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/plugins/a_common_libs/lib/tasks/saas.rake:1:in`<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `block in <top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in`each'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `<top (required)>'
/opt/redmine-3.0.3-0/apps/redmine/htdocs/Rakefile:7:in`<top (required)>'
(See full trace by running task with --trace)

**Comment by xDaemonSx** [comment]
it is not a problem of the plugin
You have not started Mysql

Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
