### ISSUE TITLE
does it support redmine 2.5?

### ISSUE THREAD

**Issue by arquio** [centosadmin/redmine_activity_report#11]
/opt/redmine# bundle exec rake redmine:plugins NAME=redmine_activity_report RAILS_ENV=production
rake aborted!
undefined method `ids' for #<Class:0x00000002e52a48>
/var/lib/gems/2.1.0/gems/activerecord-3.2.19/lib/active_record/dynamic_matchers.rb:55:in`method_missing'
/opt/redmine/plugins/redmine_activity_report/init.rb:16:in `block in <top (required)>'
/opt/redmine/lib/redmine/plugin.rb:73:in`instance_eval'
/opt/redmine/lib/redmine/plugin.rb:73:in `register'
/opt/redmine/plugins/redmine_activity_report/init.rb:6:in`<top (required)>'
/var/lib/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in`load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/opt/redmine/lib/redmine/plugin.rb:133:in`block in load'
/opt/redmine/lib/redmine/plugin.rb:124:in `each'
/opt/redmine/lib/redmine/plugin.rb:124:in`load'
/opt/redmine/config/initializers/30-redmine.rb:19:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in`load'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in`load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/engine.rb:593:in`block (2 levels) in class:Engine'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/engine.rb:592:in`block in class:Engine'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in`run'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in`each'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/application.rb:136:in`initialize!'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/opt/redmine/config/environment.rb:14:in`<top (required)>'
/var/lib/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in`load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/opt/redmine/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in`<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in`block in load'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in`load'
/opt/redmine/lib/tasks/redmine.rake:178:in `block in <top (required)>'
/opt/redmine/lib/tasks/redmine.rake:178:in`each'
/opt/redmine/lib/tasks/redmine.rake:178:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in`load'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in`load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/engine.rb:425:in`block in load_tasks'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/engine.rb:425:in `each'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/engine.rb:425:in`load_tasks'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/application.rb:145:in `load_tasks'
/var/lib/gems/2.1.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in`method_missing'
/opt/redmine/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by arturtr** [comment]
Nope. We developed it for redmine 3.1 and than continue to support it for latest redmine version (which we use)
