### ISSUE TITLE
Change name of folder

### ISSUE THREAD

**Issue by ludovicandrieux** [centosadmin/redmine_activity_report#12]
Hi,

When we clone git, we get a folder name redmine_activity_report and we put it in folder plugins.
But in reality, folder have to be "timesheet".
There is no doc and it's not really a good way to do installation so can you change your name internaly to become redmine_activity_report ?

Thanks
Ludovic

**Comment by olemskoi** [comment]
Hi Ludovic,

I have redmine_activity_report plugin in plugins folder and it works well. Can you please post log with details?

**Comment by ludovicandrieux** [comment]
Sorry. This bug is for an other plugin project. 
It's ok. You're right.
