### ISSUE TITLE
gem error

### ISSUE THREAD

**Issue by smoolya17** [centosadmin/redmine_activity_report#13]
when i tried installing the gem the bundler throws the following error:

ERROR:  Could not find a valid gem 'whenever' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect retur
ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (
https://api.rubygems.org/specs.4.8.gz)

also adding the line gem 'whenever' didnt help. Kindly advice

**Comment by olemskoi** [comment]
Probably this is problem with rubygems.
