### ISSUE TITLE
Error: undefined method `activity_report_settings'

### ISSUE THREAD

**Issue by silin4singree** [centosadmin/redmine_activity_report#15]
Ubuntu 16.04 x64
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64)

`
Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_activity_report        1.2.9
  redmine_agile                  1.4.2
  redmine_checklists             3.1.5
  redmine_ckeditor               1.1.3
  redmine_code_review            0.7.0
  redmine_contacts               4.0.6
  redmine_issue_templates        0.1.1
  redmine_lightbox2              0.2.5
  redmine_people                 1.2.0
  redmine_tweaks                 1.0.0
`

Установил плагин следующим образом: 
1. gem install whenever
2. git clone https://github.com/centosadmin/redmine_activity_report.git plugins/redmine_activity_report 
3. bundle exec rake redmine:plugins:migrate
4. bundle exec whenever -i redmine_activity_report -f plugins/redmine_activity_report/config/schedule.rb

В настройках проекта на вкладке "модули" установил признак использования модуля "activity report". После нажатия на конпку сохранить получил 500-ю ошибку. Теперь при попытке открыть вкладку настроек этого проекта в log/production.log выводится следующее: 
`  
Rendered projects/settings.html.erb within layouts/base (287.1ms)
Completed 500 Internal Server Error in 315ms (ActiveRecord: 29.6ms)

ActionView::Template::Error (undefined method `activity_report_settings' for #<Project:0x007f897f9c03c8>):
    10:     <div class="box">
    11:       <p>
    12:         <%= check_box_tag 'activity_report_settings[with_subprojects]', '1',
    13:                           @project.activity_report_settings.try(:[], 'with_subprojects').present?,
    14:                           id: 'activity_report_settings_with_subprojects'
    15:         %>
    16:         <%= label_tag 'activity_report_settings[with_subprojects]', t('activity_report.settings.with_subprojects') %>
  plugins/redmine_activity_report/app/views/projects/settings/_activity_report.html.erb:13:in `block in _d1dc3f9055d7c33e435c3d0d10d89191'
  plugins/redmine_activity_report/app/views/projects/settings/_activity_report.html.erb:7:in `_d1dc3f9055d7c33e435c3d0d10d89191'
  app/views/common/_tabs.html.erb:17:in `block in _cb4762fefee9f355ada80db890ea8e1f'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_cb4762fefee9f355ada80db890ea8e1f'
  app/helpers/application_helper.rb:325:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_ff8510739965a8347bdffd3499e4d230'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
`

Проверил еще на двух проектах - аналогично. 
Как это можно исправить?

**Comment by arturtr** [comment]
Два вопроса:
1. Что будет если в консоли рельс вызвать activity_report_settings у проекта
```
cd redmine
bundle exec rails c production
irb> Project.last.activity_report_settings
```

2. Что-либо меняется, если плагин обновить из ветки 
https://github.com/centosadmin/redmine_activity_report/tree/fix-project-helper

**Comment by arturtr** [comment]
@silin4singree жду обратной связи от вас

**Comment by olemskoi** [comment]
Напишите, если задача актуальна.
