### ISSUE TITLE
Issue during the database migration

### ISSUE THREAD

**Issue by mcolomboid** [centosadmin/redmine_activity_report#19]
Hello,
during the database migration on Redmine 2.6.9, i'm getting this error:

>  /var/www/redmine # bundle exec rake redmine:plugins:migrate RAILS_ENV=production
 
> rake aborted!
NoMethodError: undefined method `ids' for #<Class:0x000000032b67d8>
/usr/local/share/gems/gems/activerecord-3.2.22/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
/var/www/redmine-2.6.9/plugins/redmine_activity_report/init.rb:16:in `block in <top (required)>'
/var/www/redmine-2.6.9/lib/redmine/plugin.rb:75:in `instance_eval'
/var/www/redmine-2.6.9/lib/redmine/plugin.rb:75:in `register'
/var/www/redmine-2.6.9/plugins/redmine_activity_report/init.rb:6:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/var/www/redmine-2.6.9/lib/redmine/plugin.rb:150:in `block in load'
/var/www/redmine-2.6.9/lib/redmine/plugin.rb:141:in `each'
/var/www/redmine-2.6.9/lib/redmine/plugin.rb:141:in `load'
/var/www/redmine-2.6.9/config/initializers/30-redmine.rb:19:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:245:in `load'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:245:in `load'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/engine.rb:592:in `each'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/engine.rb:592:in `block in <class:Engine>'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `run'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `each'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/application.rb:136:in `initialize!'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/redmine-2.6.9/config/environment.rb:14:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/application.rb:103:in `require_environment!'
/usr/local/share/gems/gems/railties-3.2.22/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

i've installed "whenever", as requested in the documentation.
maybe a bug (?)

**Comment by olemskoi** [comment]
Hello,

Can you please try to update redmine to 3.3-stable?

**Comment by mcolomboid** [comment]
Hello,
thanks so much for the reply, i will try to upgrade to redmine 3.3 and i will let you know

**Comment by olemskoi** [comment]
Please reopen issue if problem will still persist in new version.
