### ISSUE TITLE
didnot send email

### ISSUE THREAD

**Issue by razbag** [centosadmin/redmine_activity_report#2]
Hi dear all i setup plugin work correct all settings done cron work correct but i didnot recive any email this is a trace results 
/usr/share/redmine# RAILS_ENV=production bundle exec rake activity_report:daily --trace
*\* Invoke activity_report:daily (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute activity_report:daily
Please Help me

**Comment by olemskoi** [comment]
Hello,

Did you activated module in project settings?

**Comment by razbag** [comment]
Hi ,
yes you can see it in attached files 
![1](https://cloud.githubusercontent.com/assets/18428312/14474263/3797728c-010d-11e6-8a70-8b1b3103a704.png)
![2](https://cloud.githubusercontent.com/assets/18428312/14474269/3bbf0abe-010d-11e6-875c-f97dbb50b5e2.png)

**Comment by olemskoi** [comment]
And Settings -> Modules section?

**Comment by razbag** [comment]
![3](https://cloud.githubusercontent.com/assets/18428312/14474487/6d346f5c-010e-11e6-95f3-6d4fb22cd5c0.png)
Yes

**Comment by olemskoi** [comment]
And spent time screenshot on this project please. Activity tab.

**Comment by razbag** [comment]
Please 
Activity Tab screenshot  
![4](https://cloud.githubusercontent.com/assets/18428312/14474623/17ff602c-010f-11e6-8d78-8cd9f3913b4d.png)

**Comment by olemskoi** [comment]
Is there spent time for yesterday?

**Comment by razbag** [comment]
no this is a on march 15 and 17

**Comment by olemskoi** [comment]
Plugin reports only yesterday, last week (once a week) and last month (once a month) spent time.

**Comment by razbag** [comment]
ok sorry for your time and thanks a lot i try 

RAILS_ENV=production bundle exec rake activity_report:monthly --trace
(in /usr/share/redmine)
*\* Invoke activity_report:monthly (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute activity_report:monthly

and i got email with report 
Thanks for support

**Comment by bluenevus** [comment]
I'm not getting the email  ran

RAILS_ENV=production bundle exec rake activity_report:monthly --trace
RAILS_ENV=production bundle exec rake activity_report:weekly --trace
RAILS_ENV=production bundle exec rake activity_report:daily --trace

I get the output on the screen ** Invoke activity_report:monthly (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute activity_report:monthly

No email.  followed this post to make sure I'm doing the same thing...nothing
