### ISSUE TITLE
Error: undefined method `default_url_options' 

### ISSUE THREAD

**Issue by tranrn** [centosadmin/redmine_activity_report#23]
Крон прислал ошибку. Попробовал запустить руками, те же ошибки. 4.0.1

_RAILS_ENV=production bundle exec rake activity_report:daily_ 
rake aborted!
ActionView::Template::Error: undefined method `default_url_options' for ActionMailer::Parameterized::Mailer:Class

Caused by:
NoMethodError: undefined method `default_url_options' for ActionMailer::Parameterized::Mailer:Class

**Comment by merihilgor** [comment]
remove lines :

  def self.default_url_options
    Mailer.default_url_options
  end

from :

/app/models/activity_report_mailer.rb

and add 

  ActionMailer::Base.default_url_options = { :host => "YOUR_IP:YOUR_PORT" }
  Rails.application.config.action_mailer.default_url_options = "http://YOUR_IP:YOUR_PORT/"

instead of them

**Comment by tranrn** [comment]
thanks, now ok
