### ISSUE TITLE
adding chron job

### ISSUE THREAD

**Issue by bluenevus** [centosadmin/redmine_activity_report#3]
bundle exec whenever -i redmine_activity_report -f plugins/redmine_activity_report/config/schedule.rb

I'm getting this error below

/var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:292:in `block in replace_gem': whenever is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
        from /usr/local/bin/whenever:22:in`<main>'

**Comment by bluenevus** [comment]
nevermind.  figured it out.
first whenever doesn't install automatically...must do it manually
then must add it to the gemfile manuall echo "gem 'whenever'" >> Gemfile
then run the command from the redmine directory
it works

**Comment by kunashir** [comment]
Why **whenever** have not added to plugin's  Gemfile?

**Comment by endenwer** [comment]
Because of the conflict with other plugins. If multiple plugins have the same gem in Gemfile it raises errors. You can add this gem to Gemfile.local at the root of Redmine and run 'bundle install' from the root of Redmine.
