### ISSUE TITLE
does it support redmine 3.2.X?

### ISSUE THREAD

**Issue by archonwang** [centosadmin/redmine_activity_report#7]
I tried it on Redmine 3.2.1, I config the plugin as follows
1. installed the plugin and config the plugin settings
2. in projects add [activity_user], [report_user]
3. config the schedule.rb
4. restart redmine

I wait until the time I have defined, but nothing happened after I make these config... 
anything I've missed? Thanks.

**Comment by olemskoi** [comment]
Did you started whenever after "config the schedule.rb"?

## 

Олемской Игорь
Компания "Southbridge"

+7 (495) 66-55-027 доб.77
www.southbridge.ru

**Comment by archonwang** [comment]
@olemskoi  
I just use the command as readme told me.

> bundle exec whenever -i redmine_activity_report -f plugins/redmine_activity_report/config/schedule.rb

 Should I start whenever?  How to start it? Thanks.

**Comment by archonwang** [comment]
I checked my cronb file and found these commands

> # Begin Whenever generated tasks for: redmine_activity_report
> 
> 37 23 \* \* \* /bin/bash -l -c 'cd /opt/redmine && RAILS_ENV=production bundle exec rake activity_report:daily --silent'
> 20 12 \* \* 1 /bin/bash -l -c 'cd /opt/redmine && RAILS_ENV=production bundle exec rake activity_report:weekly --silent'
> 30 12 1 \* \* /bin/bash -l -c 'cd /opt/redmine && RAILS_ENV=production bundle exec rake activity_report:monthly --silent'
> 
> # End Whenever generated tasks for: redmine_activity_report

so I use the command to test:

> RAILS_ENV=production bundle exec rake activity_report:daily

it happened nothing , and there's no error log? so, anything I have missed? Thanks.

**Comment by olemskoi** [comment]
Can you please look at https://github.com/centosadmin/redmine_activity_report/issues/2 ?
Did you tracked spent time yesterday?

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.

**Comment by archonwang** [comment]
Thanks so much. 
I think I missed the spent time.
